apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-catalog
  region: us-east-2
  version: "1.21"
managedNodeGroups:
- name: primary
  instanceType: t2.small
  minSize: 2
  maxSize: 3
  spot: true
