# Generated by Django 4.0 on 2021-12-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0006_alter_entrenadorpokemones_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=100)),
            ],
        ),
    ]
