# Generated by Django 4.0 on 2021-12-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0007_trivia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trivia',
        ),
    ]
